import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import SectionCards from "../components/SectionCards";

const cairoFont = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dev Case | Işıksoft",
  description: "Generated by Furkan Can",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cairoFont.variable} antialiased flex`}>
        <Navbar />

        <div className="w-full bg-background flex flex-col gap-2 sm:gap-5 md:gap-[30px] px-2 sm:px-5 pt-2 sm:pt-5 pb-[30px]">
          <Header />
          <SectionCards />

          {children}
        </div>
      </body>
    </html>
  );
}
